import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  scrollContent: { padding: 20, paddingBottom: 100 },
  header: { marginBottom: 30, marginTop: 20 },
  greeting: { fontSize: 16, color: '#64748B' },
  title: { fontSize: 28, fontWeight: 'bold', color: '#1E293B' },
  cycleCircle: {
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'white',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 10,
    borderColor: '#FFE4E6',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    marginBottom: 40,
  },
  dayNumber: { fontSize: 60, fontWeight: '900', color: '#1E293B' },
  dayLabel: { fontSize: 12, color: '#94A3B8', letterSpacing: 1 },
  aiCard: {
    backgroundColor: '#EEF2FF',
    padding: 20,
    borderRadius: 20,
    borderLeftWidth: 5,
    borderLeftColor: '#6366F1',
    marginBottom: 20,
  },
  row: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, gap: 8 },
  aiTitle: { fontWeight: 'bold', color: '#4338CA', fontSize: 12, flex: 1 },
  aiText: { color: '#3730A3', lineHeight: 22, marginBottom: 2 },
  confidenceBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  confidenceText: { color: 'white', fontSize: 10, fontWeight: '700' },
  grid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 },
  statBox: { backgroundColor: 'white', padding: 15, borderRadius: 16, width: '48%', elevation: 2 },
  statLabel: { fontSize: 12, color: '#64748B', marginTop: 8 },
  statValue: { fontSize: 16, fontWeight: 'bold', color: '#1E293B' },
  subtext: { textAlign: 'center', color: '#94A3B8', fontSize: 13, marginTop: 4 },
  errorCard: {
    backgroundColor: '#FEE2E2',
    padding: 20,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 40,
  },
  errorText: { color: '#991B1B', textAlign: 'center', marginBottom: 12 },
  retryButton: { backgroundColor: '#EF4444', paddingHorizontal: 20, paddingVertical: 8, borderRadius: 10 },
  retryText: { color: 'white', fontWeight: '700' },
  fab: {
    position: 'absolute',
    bottom: 30,
    right: 30,
    backgroundColor: '#FF6B6B',
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
  },
});